# This file was generated by GoReleaser. DO NOT EDIT.
cask "testoptim" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "b1684e335f37dc9a809c05255630aadc40e880fb9010f5f86919fc2f692811f8"
      url "https://github.com/TestOptim-AI/testoptim-cli/releases/download/cli-v#{version}/testoptim_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cb7d78aa1b5ebaa5d8fe210e5003e03325c2398e410593362911e82473b3a996"
      url "https://github.com/TestOptim-AI/testoptim-cli/releases/download/cli-v#{version}/testoptim_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "9699093e9a7d3cc4008f85b5858a75891a283724cad4123c3d134890e28e52b6"
      url "https://github.com/TestOptim-AI/testoptim-cli/releases/download/cli-v#{version}/testoptim_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "8c485567da1f2cd568edacc4b42992b4e8841b495ac56cc4558113f833a6799f"
      url "https://github.com/TestOptim-AI/testoptim-cli/releases/download/cli-v#{version}/testoptim_#{version}_linux_amd64.tar.gz"
    end
  end

  name "testoptim"
  desc "Private tunnel and tools for TestOptim"
  homepage "https://testoptim.ai"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "testoptim"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/testoptim"]
    end
  end

  # No zap stanza required
end
